export const EFFECT_NAMES: Record<string, string> = {
  goldenDust: "Golden Dust", starfield: "Starfield", auroraWave: "Aurora Wave",
  neonGrid: "Neon Grid", fireEmbers: "Fire Embers", electricStorm: "Electric Storm",
  cinemaGrain: "Cinema Grain", smokeRing: "Smoke Ring", matrixRain: "Matrix Rain",
  plasmaField: "Plasma Field", rainfall: "Rainfall", dnaHelix: "DNA Helix",
  cosmicDust: "Cosmic Dust", blackHole: "Black Hole", galaxy: "Galaxy",
  meteorShower: "Meteor Shower", interactiveParticles: "Interactive Particles",
  blurredGradients: "Blurred Gradients", parallaxField: "Parallax Field",
  animatedShapes: "Animated Shapes", nebula: "Nebula", oceanWaves: "Ocean Waves",
  snowfall: "Snowfall", fireflies: "Fireflies", lightningBolts: "Lightning Bolts",
  vortexTunnel: "Vortex Tunnel", northernLights: "Northern Lights",
  raindropRipples: "Raindrop Ripples", lavaLamp: "Lava Lamp",
  crystalMatrix: "Crystal Matrix", digitalCircuit: "Digital Circuit",
  solarFlare: "Solar Flare", geometricTessellation: "Geometric Tessellation",
  inkBleed: "Ink Bleed", glitchWave: "Glitch Wave", kaleidoscope: "Kaleidoscope",
  waveInterference: "Wave Interference", cellularAutomata: "Cellular Automata",
  fractalTree: "Fractal Tree", holographicShimmer: "Holographic Shimmer",
  magneticField: "Magnetic Field", retroSunset: "Retro Sunset",
  quantumField: "Quantum Field", coralReef: "Coral Reef", acidTrip: "Acid Trip",
  tidalWave: "Tidal Wave", crystalGrowth: "Crystal Growth",
  fireworksBurst: "Fireworks Burst", topography: "Topography",
  prismRefraction: "Prism Refraction", powerNexus: "Power Nexus",
  sandStorm: "Sand Storm", bubbleRise: "Bubble Rise", gravityWell: "Gravity Well",
  neuralNetwork: "Neural Network", pendulum: "Pendulum", flockingBoids: "Flocking Boids",
  pixelSort: "Pixel Sort", spiralGalaxy: "Spiral Galaxy", waterColor: "Water Color",
  chandelier: "Chandelier",
  morningDew: "Morning Dew",
  cherryBlossom: "Cherry Blossom",
  mintBreeze: "Mint Breeze",
  freshSplash: "Fresh Splash",
  springBloom: "Spring Bloom",
};
